# market_backtest.py
"""
Multi-Market Backtesting - Analyze all Tier 1+2 markets over 4-week period
Identifies which markets have the best accuracy and profitability
"""

import sys, io
if hasattr(sys.stdout, 'buffer'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace', line_buffering=True)

import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Tuple

from config import OUTPUT_DIR, DATA_DIR

# Tier 1+2 Market Configurations

# Per-market confidence floors derived from threshold_analysis.py (2026-07-02, tuned params).
# Only markets with a +ROI threshold are listed; dead-weight markets set to 0.99 (effectively excluded).
# NOTE: thresholds below 70% (OU_2_5, BTTS, HomeTeam_Card) are NOT used for auto_tune scoring
# (global floor is 70%) but apply for final predict output and threshold_analysis.
# Re-run threshold_analysis.py after each FULL retrain to refresh these.
MARKET_MIN_CONF = {
    # OU markets (BLEND)
    'OU_0_5':  0.96,   # 64 preds,  100% acc, +2.9% ROI
    'OU_1_5':  0.85,   # 20 preds,  100% acc, +15.1% ROI
    'OU_2_5':  0.70,   # 39 preds,  87.2% acc, +31.6% ROI (optimal 63% but clamped to global floor)
    'OU_3_5':  0.83,   # 24 preds,  95.8% acc, +12.7% ROI
    'OU_4_5':  0.94,   # 21 preds,  100% acc, +5.5% ROI
    # TG markets (BLEND)
    'HomeTG_0_5': 0.92,  # 42 preds, 97.6% acc, +3.2% ROI
    'HomeTG_1_5': 0.99,  # no +ROI threshold
    'AwayTG_0_5': 0.99,  # no +ROI threshold
    'AwayTG_1_5': 0.99,  # no +ROI threshold
    # 1X2 (BLEND) — no profitable threshold
    '1X2': 0.99,
    # BTTS (optimal 66% but clamped to global floor for tuning)
    'BTTS': 0.71,
    # YC/cards (ML, temperature_binary=10.0)
    'TotalYC_O1_5': 0.68,  # 264 preds, 89.8% acc, +31.7% ROI (optimal 50% but 68% used for tuning)
    'TotalYC_O2_5': 0.68,  # 191 preds, 76.4% acc, +11.6% ROI
    'TotalYC_O6_5': 0.50,  # 264 preds, 83.7% acc, +17.3% ROI
    'TotalYC_O3_5': 0.99,  # no +ROI threshold
    'TotalYC_O4_5': 0.99,  # no +ROI threshold
    'TotalYC_O5_5': 0.99,  # no +ROI threshold
    'HomeTeam_Card': 0.68, # 259 preds, 85.7% acc, +25.0% ROI (optimal 63% but 68% used for tuning)
    'AwayTeam_Card': 0.68, # 230 preds, 90.4% acc, +31.4% ROI
    'BookingPts_O20_5': 0.70,  # 171 preds, 80.7% acc, +15.2% ROI
    'BookingPts_O30_5': 0.99,  # no +ROI threshold
    'BookingPts_O40_5': 0.99,  # no +ROI threshold
    # Corners (ML)
    'TotalCorners_O6_5':  0.72,  # 235 preds, 83.4% acc, +15.3% ROI
    'TotalCorners_O11_5': 0.74,  # 225 preds, 79.1% acc, +0.1% ROI
    'TotalCorners_O12_5': 0.73,  # 245 preds, 86.9% acc, +9.5% ROI
    'TotalCorners_O7_5':  0.99,  # no +ROI threshold
    'TotalCorners_O8_5':  0.99,  # no +ROI threshold
    'TotalCorners_O9_5':  0.99,  # no +ROI threshold
    'TotalCorners_O10_5': 0.99,  # no +ROI threshold
    'HomeCorners_O4_5':   0.99,  # no +ROI threshold
    'HomeCorners_O5_5':   0.99,  # no +ROI threshold
    'AwayCorners_O4_5':   0.99,  # no +ROI threshold
    'AwayCorners_O5_5':   0.99,  # no +ROI threshold
    'HomeCorners_Win':    0.99,  # no +ROI threshold
    # HTFT
    'HTFT': 0.99,  # no +ROI threshold
}

# Per-league thresholds (generated by threshold_analysis.py --by-league).
# Structure: league_code -> market_name -> float threshold (0-1).
# Overrides MARKET_MIN_CONF when a match's league has a specific entry.
import json as _json
_LEAGUE_THRESH_PATH = Path(__file__).parent / 'outputs' / 'league_thresholds.json'
try:
    LEAGUE_MARKET_CONF: dict = _json.loads(_LEAGUE_THRESH_PATH.read_text()) if _LEAGUE_THRESH_PATH.exists() else {}
except Exception:
    LEAGUE_MARKET_CONF = {}

MARKET_CONFIGS = {
    # TIER 1: Core Markets
    '1X2': {
        'actual_col': 'FTR',
        'pred_cols': ['P_1X2_H', 'P_1X2_D', 'P_1X2_A'],
        'outcomes': ['H', 'D', 'A'],
        'type': 'multiclass'
    },
    'BTTS': {
        'actual_col': 'y_BTTS',
        'pred_cols': ['P_BTTS_Y', 'P_BTTS_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    },
    'OU_0_5': {
        'actual_col': 'y_OU_0_5',
        'pred_cols': ['P_OU_0_5_O', 'P_OU_0_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    'OU_1_5': {
        'actual_col': 'y_OU_1_5',
        'pred_cols': ['P_OU_1_5_O', 'P_OU_1_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    'OU_2_5': {
        'actual_col': 'y_OU_2_5',
        'pred_cols': ['P_OU_2_5_O', 'P_OU_2_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    'OU_3_5': {
        'actual_col': 'y_OU_3_5',
        'pred_cols': ['P_OU_3_5_O', 'P_OU_3_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    'OU_4_5': {
        'actual_col': 'y_OU_4_5',
        'pred_cols': ['P_OU_4_5_O', 'P_OU_4_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    # TIER 2: Value Markets
    'HomeTG_0_5': {
        'actual_col': 'y_HomeTG_0_5',
        'pred_cols': ['P_HomeTG_0_5_O', 'P_HomeTG_0_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    'HomeTG_1_5': {
        'actual_col': 'y_HomeTG_1_5',
        'pred_cols': ['P_HomeTG_1_5_O', 'P_HomeTG_1_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    'AwayTG_0_5': {
        'actual_col': 'y_AwayTG_0_5',
        'pred_cols': ['P_AwayTG_0_5_O', 'P_AwayTG_0_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    'AwayTG_1_5': {
        'actual_col': 'y_AwayTG_1_5',
        'pred_cols': ['P_AwayTG_1_5_O', 'P_AwayTG_1_5_U'],
        'outcomes': ['O', 'U'],
        'type': 'binary'
    },
    # TIER 3: Cards Markets (trained in FULL mode)
    **{f'TotalYC_O{str(line).replace(".", "_")}': {
        'actual_col': f'y_TotalYC_O{str(line).replace(".", "_")}',
        'pred_cols': [f'P_TotalYC_O{str(line).replace(".", "_")}_Y',
                      f'P_TotalYC_O{str(line).replace(".", "_")}_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    } for line in [1.5, 2.5, 3.5, 4.5, 5.5, 6.5]},
    **{f'BookingPts_O{str(line).replace(".", "_")}': {
        'actual_col': f'y_BookingPts_O{str(line).replace(".", "_")}',
        'pred_cols': [f'P_BookingPts_O{str(line).replace(".", "_")}_Y',
                      f'P_BookingPts_O{str(line).replace(".", "_")}_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    } for line in [20.5, 30.5, 40.5]},
    'HomeTeam_Card': {
        'actual_col': 'y_HomeTeam_Card',
        'pred_cols': ['P_HomeTeam_Card_Y', 'P_HomeTeam_Card_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    },
    'AwayTeam_Card': {
        'actual_col': 'y_AwayTeam_Card',
        'pred_cols': ['P_AwayTeam_Card_Y', 'P_AwayTeam_Card_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    },
    # TIER 3: Corners Markets (trained in FULL mode)
    **{f'TotalCorners_O{str(line).replace(".", "_")}': {
        'actual_col': f'y_TotalCorners_O{str(line).replace(".", "_")}',
        'pred_cols': [f'P_TotalCorners_O{str(line).replace(".", "_")}_Y',
                      f'P_TotalCorners_O{str(line).replace(".", "_")}_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    } for line in [6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5]},
    **{f'HomeCorners_O{str(line).replace(".", "_")}': {
        'actual_col': f'y_HomeCorners_O{str(line).replace(".", "_")}',
        'pred_cols': [f'P_HomeCorners_O{str(line).replace(".", "_")}_Y',
                      f'P_HomeCorners_O{str(line).replace(".", "_")}_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    } for line in [4.5, 5.5]},
    **{f'AwayCorners_O{str(line).replace(".", "_")}': {
        'actual_col': f'y_AwayCorners_O{str(line).replace(".", "_")}',
        'pred_cols': [f'P_AwayCorners_O{str(line).replace(".", "_")}_Y',
                      f'P_AwayCorners_O{str(line).replace(".", "_")}_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    } for line in [4.5, 5.5]},
    'HomeCorners_Win': {
        'actual_col': 'y_HomeCorners_Win',
        'pred_cols': ['P_HomeCorners_Win_Y', 'P_HomeCorners_Win_N'],
        'outcomes': ['Y', 'N'],
        'type': 'binary'
    },
    # HTFT — Half-time / Full-time result (9-class)
    'HTFT': {
        'actual_col': 'y_HTFT',
        'pred_cols': [f'P_HTFT_{a}_{b}' for a in ['H','D','A'] for b in ['H','D','A']],
        'outcomes': [f'{a}-{b}' for a in ['H','D','A'] for b in ['H','D','A']],
        'type': 'multiclass'
    },
}


class MarketBacktester:
    """Analyze all markets using walk-forward backtest on historical data"""

    def __init__(self, weeks: int = 4, min_confidence: float = 0.90, use_historical: bool = True):
        """
        Args:
            weeks: Number of weeks to analyze
            min_confidence: Minimum confidence threshold (default 90%)
            use_historical: If True, run walk-forward backtest on historical data
                          If False, analyze recent predictions (for live tracking)
        """
        self.weeks = weeks
        self.min_confidence = min_confidence
        self.use_historical = use_historical
        self.results = []

    def load_weekly_predictions(self, week_folders: List[Path]) -> pd.DataFrame:
        """Load predictions from multiple week folders"""
        all_preds = []

        for folder in week_folders:
            csv_file = folder / "weekly_bets.csv"
            if csv_file.exists():
                df = pd.read_csv(csv_file)
                df['Week'] = folder.name
                all_preds.append(df)
                print(f"[OK] Loaded {len(df)} predictions from {folder.name}")
            else:
                print(f"[WARN] No predictions found in {folder.name}")

        if not all_preds:
            raise FileNotFoundError("No prediction files found")

        combined = pd.concat(all_preds, ignore_index=True)
        print(f"\n[OK] Total predictions: {len(combined)} across {len(all_preds)} weeks")
        return combined

    def load_actual_results(self, start_date=None, end_date=None) -> pd.DataFrame:
        """Load actual match results from API-Football database and calculate targets"""
        from api_football_adapter import get_fixtures_from_db

        # Get all completed matches from database
        df = get_fixtures_from_db(status='FT')

        # Filter completed matches only (must have result)
        df = df[df['FTR'].notna()].copy()
        df['Date'] = pd.to_datetime(df['Date'])

        # Filter by date range if specified
        if start_date:
            df = df[df['Date'] >= pd.to_datetime(start_date)]
        if end_date:
            df = df[df['Date'] <= pd.to_datetime(end_date)]

        # Calculate target columns from raw match data
        df = self._calculate_target_columns(df)

        print(f"[OK] Loaded {len(df)} completed matches with results")
        return df

    def _calculate_target_columns(self, df: pd.DataFrame) -> pd.DataFrame:
        """Calculate all target columns (y_*) from raw match data"""
        import numpy as np

        # Total goals
        total = df['FTHG'] + df['FTAG']

        # 1X2 - already have FTR
        df['y_1X2'] = df['FTR'].astype(str)

        # BTTS
        btts = (df['FTHG'] > 0) & (df['FTAG'] > 0)
        df['y_BTTS'] = np.where(btts, 'Y', 'N')

        # Over/Under lines
        for line in [0.5, 1.5, 2.5, 3.5, 4.5, 5.5]:
            line_str = str(line).replace('.', '_')
            df[f'y_OU_{line_str}'] = np.where(total > line, 'O', 'U')

        # Double Chance
        df['y_DC_1X'] = np.where(df['FTR'].isin(['H', 'D']), 'Y', 'N')
        df['y_DC_12'] = np.where(df['FTR'].isin(['H', 'A']), 'Y', 'N')
        df['y_DC_X2'] = np.where(df['FTR'].isin(['D', 'A']), 'Y', 'N')

        # Draw No Bet
        df['y_DNB_H'] = np.where(df['FTR'] == 'H', 'Y', np.where(df['FTR'] == 'D', 'P', 'N'))
        df['y_DNB_A'] = np.where(df['FTR'] == 'A', 'Y', np.where(df['FTR'] == 'D', 'P', 'N'))

        # Team to Score
        df['y_HomeToScore'] = np.where(df['FTHG'] > 0, 'Y', 'N')
        df['y_AwayToScore'] = np.where(df['FTAG'] > 0, 'Y', 'N')

        # Home Team Goals O/U
        df['y_HomeTG_0_5'] = np.where(df['FTHG'] > 0.5, 'O', 'U')
        df['y_HomeTG_1_5'] = np.where(df['FTHG'] > 1.5, 'O', 'U')

        # Away Team Goals O/U
        df['y_AwayTG_0_5'] = np.where(df['FTAG'] > 0.5, 'O', 'U')
        df['y_AwayTG_1_5'] = np.where(df['FTAG'] > 1.5, 'O', 'U')

        # Asian Handicap (simplified - just goal difference)
        goal_diff = df['FTHG'] - df['FTAG']
        df['y_AH_-0_5'] = np.where(goal_diff > 0.5, 'H', np.where(goal_diff < -0.5, 'A', 'P'))
        df['y_AH_+0_5'] = np.where(goal_diff > -0.5, 'H', np.where(goal_diff < 0.5, 'A', 'P'))
        df['y_AH_-1_0'] = np.where(goal_diff > 1, 'H', np.where(goal_diff < -1, 'A', 'P'))
        df['y_AH_+1_0'] = np.where(goal_diff > -1, 'H', np.where(goal_diff < 1, 'A', 'P'))
        df['y_AH_0_0'] = np.where(goal_diff > 0, 'H', np.where(goal_diff < 0, 'A', 'P'))

        # Result + BTTS Combinations
        df['y_HomeWin_BTTS_Y'] = np.where((df['FTR'] == 'H') & btts, 'Y', 'N')
        df['y_AwayWin_BTTS_Y'] = np.where((df['FTR'] == 'A') & btts, 'Y', 'N')
        df['y_HomeWin_BTTS_N'] = np.where((df['FTR'] == 'H') & ~btts, 'Y', 'N')
        df['y_AwayWin_BTTS_N'] = np.where((df['FTR'] == 'A') & ~btts, 'Y', 'N')

        # DC + O/U Combinations
        df['y_DC1X_O25'] = np.where((df['FTR'].isin(['H', 'D'])) & (total > 2.5), 'Y', 'N')
        df['y_DCX2_O25'] = np.where((df['FTR'].isin(['D', 'A'])) & (total > 2.5), 'Y', 'N')

        # Cards markets (if card data available from DB)
        home_cy = 'Home_CardsY' if 'Home_CardsY' in df.columns else ('HY' if 'HY' in df.columns else None)
        away_cy = 'Away_CardsY' if 'Away_CardsY' in df.columns else ('AY' if 'AY' in df.columns else None)
        home_cr = 'Home_CardsR' if 'Home_CardsR' in df.columns else ('HR' if 'HR' in df.columns else None)
        away_cr = 'Away_CardsR' if 'Away_CardsR' in df.columns else ('AR' if 'AR' in df.columns else None)
        if home_cy and away_cy:
            total_cy = pd.to_numeric(df[home_cy], errors='coerce').fillna(0) + \
                       pd.to_numeric(df[away_cy], errors='coerce').fillna(0)
            for line in [1.5, 2.5, 3.5, 4.5, 5.5, 6.5]:
                tag = str(line).replace('.', '_')
                df[f'y_TotalYC_O{tag}'] = np.where(total_cy > line, 'Y', 'N')
            if home_cr and away_cr:
                total_bp = total_cy * 10 + \
                    (pd.to_numeric(df[home_cr], errors='coerce').fillna(0) +
                     pd.to_numeric(df[away_cr], errors='coerce').fillna(0)) * 25
            else:
                total_bp = total_cy * 10
            for line in [20.5, 30.5, 40.5, 50.5]:
                tag = str(line).replace('.', '_')
                df[f'y_BookingPts_O{tag}'] = np.where(total_bp > line, 'Y', 'N')
            df['y_HomeTeam_Card'] = np.where(
                pd.to_numeric(df[home_cy], errors='coerce').fillna(0) > 0, 'Y', 'N')
            df['y_AwayTeam_Card'] = np.where(
                pd.to_numeric(df[away_cy], errors='coerce').fillna(0) > 0, 'Y', 'N')

        # HT/FT combo (requires half-time scores)
        if 'HTHG' in df.columns and 'HTAG' in df.columns:
            hthg = pd.to_numeric(df['HTHG'], errors='coerce')
            htag = pd.to_numeric(df['HTAG'], errors='coerce')
            ht_r = np.where(hthg > htag, 'H', np.where(hthg < htag, 'A', 'D'))
            df['y_HTFT'] = np.where(
                hthg.notna() & htag.notna(),
                pd.Series(ht_r, index=df.index) + '-' + df['FTR'].astype(str),
                np.nan
            )

        # Corners markets (if corner data available from DB)
        home_cor = 'Home_Corners' if 'Home_Corners' in df.columns else ('HC' if 'HC' in df.columns else None)
        away_cor = 'Away_Corners' if 'Away_Corners' in df.columns else ('AC' if 'AC' in df.columns else None)
        if home_cor and away_cor:
            total_corners = pd.to_numeric(df[home_cor], errors='coerce').fillna(0) + \
                            pd.to_numeric(df[away_cor], errors='coerce').fillna(0)
            for line in [6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5, 13.5]:
                tag = str(line).replace('.', '_')
                df[f'y_TotalCorners_O{tag}'] = np.where(total_corners > line, 'Y', 'N')
            hcor = pd.to_numeric(df[home_cor], errors='coerce').fillna(0)
            acor = pd.to_numeric(df[away_cor], errors='coerce').fillna(0)
            for line in [3.5, 4.5, 5.5, 6.5]:
                tag = str(line).replace('.', '_')
                df[f'y_HomeCorners_O{tag}'] = np.where(hcor > line, 'Y', 'N')
                df[f'y_AwayCorners_O{tag}'] = np.where(acor > line, 'Y', 'N')
            df['y_HomeCorners_Win'] = np.where(hcor > acor, 'Y', 'N')

        return df

    def _league_breakdown(self, merged: pd.DataFrame, output_dir: Path = None):
        """Print and save per-league accuracy/ROI for active markets."""
        if 'League' not in merged.columns:
            return

        active_markets = [m for m, floor in MARKET_MIN_CONF.items() if floor < 0.99]
        rows = []
        for league in sorted(merged['League'].unique()):
            df_lg = merged[merged['League'] == league]
            for market_name in active_markets:
                if market_name not in MARKET_CONFIGS:
                    continue
                config = MARKET_CONFIGS[market_name]
                pred_cols = config['pred_cols']
                actual_col = config['actual_col']
                outcomes = config['outcomes']
                blend_cols = [c.replace('P_', 'BLEND_') for c in pred_cols if c.startswith('P_')]
                if blend_cols and all(c in df_lg.columns for c in blend_cols):
                    pred_cols = blend_cols
                missing = [c for c in pred_cols if c not in df_lg.columns]
                if missing or actual_col not in df_lg.columns:
                    continue
                floor = MARKET_MIN_CONF.get(market_name, self.min_confidence)
                df_m = df_lg.copy()
                df_m['MaxProb'] = df_m[pred_cols].max(axis=1)
                df_m = df_m[df_m['MaxProb'] >= floor]
                if len(df_m) < 5:
                    continue
                col_to_outcome = dict(zip(pred_cols, outcomes))
                df_m['PredOutcome'] = df_m[pred_cols].idxmax(axis=1).map(col_to_outcome)
                df_m['Correct'] = df_m['PredOutcome'] == df_m[actual_col].astype(str)
                acc = df_m['Correct'].mean()
                # Fair ROI
                total_stake = len(df_m)
                total_return = sum(1.0 / row[pred_cols].max() for _, row in df_m[df_m['Correct']].iterrows())
                roi = (total_return - total_stake) / total_stake * 100 if total_stake > 0 else 0.0
                rows.append({'League': league, 'Market': market_name,
                             'Preds': total_stake, 'Acc': acc, 'ROI_Fair': roi})

        if not rows:
            return
        df_lb = pd.DataFrame(rows).sort_values(['Market', 'ROI_Fair'], ascending=[True, False])

        print("\n" + "="*70)
        print("PER-LEAGUE BREAKDOWN (active markets, floor thresholds applied)")
        print("="*70)
        current_market = None
        for _, r in df_lb.iterrows():
            if r['Market'] != current_market:
                current_market = r['Market']
                print(f"\n  {current_market}")
                print(f"  {'League':<8} {'Preds':>5} {'Acc':>6} {'ROI':>8}")
                print(f"  {'-'*30}")
            roi_str = f"{r['ROI_Fair']:+.1f}%"
            print(f"  {r['League']:<8} {int(r['Preds']):>5} {r['Acc']:>5.1%} {roi_str:>8}")

        if output_dir:
            lb_path = output_dir / "league_breakdown.csv"
            df_lb.to_csv(lb_path, index=False)
            print(f"\n[OK] Saved league breakdown -> {lb_path}")

    def run_historical_backtest(self, by_league: bool = False) -> pd.DataFrame:
        """
        Run walk-forward backtest on historical data

        This generates predictions for historical matches and evaluates them
        against actual results we already know.
        """
        from datetime import timedelta

        print("="*60)
        print(f"WALK-FORWARD HISTORICAL BACKTEST ({self.weeks} weeks)")
        print("="*60)
        print(f"Minimum confidence: {self.min_confidence:.0%}")
        print(f"Markets analyzed: {len(MARKET_CONFIGS)}")
        print()

        # Load all historical data
        print("[1/5] Loading historical match results...")
        all_results = self.load_actual_results()

        # Get the most recent completed matches for our test period
        all_results = all_results.sort_values('Date', ascending=False)

        # Calculate date range for test period (last N weeks of completed matches)
        latest_date = all_results['Date'].max()
        test_start_date = latest_date - timedelta(weeks=self.weeks)

        print(f"[INFO] Test period: {test_start_date.strftime('%Y-%m-%d')} to {latest_date.strftime('%Y-%m-%d')}")

        # Get test matches
        test_matches = all_results[
            (all_results['Date'] >= test_start_date) &
            (all_results['Date'] <= latest_date)
        ].copy()

        print(f"[OK] Found {len(test_matches)} completed matches in test period")

        if len(test_matches) == 0:
            print("[ERROR] No completed matches in test period")
            return pd.DataFrame()

        # Generate predictions for these historical matches
        print("\n[2/5] Generating predictions for historical matches...")
        predictions_df = self.generate_historical_predictions(test_matches)

        if predictions_df is None or len(predictions_df) == 0:
            print("[ERROR] Failed to generate predictions")
            return pd.DataFrame()

        print(f"[OK] Generated predictions for {len(predictions_df)} matches")

        # Merge predictions with actual results
        print("\n[3/5] Merging predictions with actual results...")
        merged = self.merge_predictions_with_results(predictions_df, test_matches)

        if len(merged) == 0:
            print("[ERROR] No matches found between predictions and results")
            return pd.DataFrame()

        print(f"[OK] Matched {len(merged)} predictions with results")

        # Merge bookmaker odds for realistic ROI
        try:
            from odds_utils import merge_odds_into_df
            merged = merge_odds_into_df(merged)
        except Exception as e:
            print(f"[INFO] Odds not available for backtest: {e}")

        # Evaluate each market
        print("\n[4/5] Evaluating market performance...")
        print("="*60)

        market_results = []
        for market_name, config in MARKET_CONFIGS.items():
            result = self.evaluate_market(merged, market_name, config)
            market_results.append(result)

            if 'error' in result:
                print(f"  {market_name:20s} [SKIP] {result['error']}")
            else:
                roi_str = f"Cnsv: {result['roi_fair']:+6.1f}%"
                if result.get('roi_actual') is not None:
                    roi_str += f" | Actual: {result['roi_actual']:+6.1f}% ({result['odds_coverage']:.0%} coverage)"
                src = result.get('pred_source', 'ML')
                print(f"  {market_name:20s} [{src}] {result['total_predictions']:4d} preds, {result['accuracy']:5.1%} acc, {roi_str}")

        # Convert to DataFrame
        df_results = pd.DataFrame(market_results)

        # Filter out markets with errors or no predictions
        df_results = df_results[df_results['total_predictions'] > 0].copy()

        # Sort by accuracy (descending)
        df_results = df_results.sort_values('accuracy', ascending=False)

        # Save raw per-match predictions + actuals for auto_tune caching
        from config import OUTPUT_DIR
        output_dir = OUTPUT_DIR.parent if OUTPUT_DIR.name.startswith('20') else OUTPUT_DIR
        cache_path = output_dir / "tuning_preds_cache.parquet"
        try:
            merged.to_parquet(cache_path, index=False)
            print(f"[OK] Saved prediction cache ({len(merged)} matches) -> {cache_path}")
        except Exception as _e:
            print(f"[WARN] Could not save prediction cache: {_e}")

        # Save results
        print("\n[5/5] Saving analysis...")
        csv_path = output_dir / "market_backtest_analysis.csv"
        df_results.to_csv(csv_path, index=False)
        print(f"[OK] Saved analysis to {csv_path}")

        # Generate HTML report
        self.generate_html_report(df_results, output_dir)

        # Per-league breakdown (only when explicitly requested)
        if by_league:
            self._league_breakdown(merged, output_dir)

        return df_results

    def generate_historical_predictions(self, test_matches: pd.DataFrame) -> pd.DataFrame:
        """
        Generate predictions for historical matches using trained models

        Args:
            test_matches: DataFrame of historical matches we want to evaluate

        Returns:
            DataFrame with predictions (P_ columns) for the test matches
        """
        import tempfile
        import os
        from predict import predict_week
        from config import OUTPUT_DIR

        # Create temporary fixtures file from historical matches
        # Include referee if available so referee features work during backtest
        fix_cols = ['Date', 'League', 'HomeTeam', 'AwayTeam']
        if 'referee' in test_matches.columns:
            fix_cols.append('referee')
        temp_fixtures = test_matches[fix_cols].copy()

        # Add Time column if it doesn't exist (set to default 15:00 for historical matches)
        if 'Time' not in temp_fixtures.columns:
            temp_fixtures['Time'] = '15:00'

        # Create temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False, newline='') as f:
            temp_path = f.name

        # Write to CSV
        temp_fixtures.to_csv(temp_path, index=False)
        print(f"  Created temporary fixtures file with {len(temp_fixtures)} matches")

        try:
            # Generate predictions using the trained models
            print(f"  Generating predictions using trained models...")
            predict_week(temp_path)

            # Load the generated predictions
            predictions_file = OUTPUT_DIR / "weekly_bets_full.csv"
            if not predictions_file.exists():
                predictions_file = OUTPUT_DIR / "weekly_bets.csv"

            if not predictions_file.exists():
                print(f"  [ERROR] Predictions not generated at {OUTPUT_DIR}")
                return None

            predictions = pd.read_csv(predictions_file)
            predictions['Date'] = pd.to_datetime(predictions['Date'])

            print(f"  [OK] Generated predictions for {len(predictions)} matches")
            return predictions

        finally:
            # Clean up temporary file
            if os.path.exists(temp_path):
                os.remove(temp_path)

    def merge_predictions_with_results(self,
                                       predictions: pd.DataFrame,
                                       results: pd.DataFrame) -> pd.DataFrame:
        """Merge predictions with actual results"""
        # Ensure date columns are datetime
        predictions['Date'] = pd.to_datetime(predictions['Date'])
        results['Date'] = pd.to_datetime(results['Date'])

        # Merge on match identifiers
        merged = predictions.merge(
            results,
            on=['Date', 'League', 'HomeTeam', 'AwayTeam'],
            how='inner',
            suffixes=('_pred', '_actual')
        )

        # Preserve fixture_id for odds lookup (may come from results side as _actual suffix)
        if 'fixture_id' not in merged.columns:
            if 'fixture_id_actual' in merged.columns:
                merged['fixture_id'] = merged['fixture_id_actual']
            elif 'fixture_id_pred' in merged.columns:
                merged['fixture_id'] = merged['fixture_id_pred']

        print(f"[OK] Matched {len(merged)} predictions with actual results")
        return merged

    def evaluate_market(self, df: pd.DataFrame, market_name: str, config: dict) -> dict:
        """Evaluate single market accuracy"""
        actual_col = config['actual_col']
        pred_cols = config['pred_cols']
        outcomes = config['outcomes']

        # Prefer BLEND_ columns over P_ columns when available (BLEND = calibrated ML+DC)
        blend_cols = [c.replace('P_', 'BLEND_') for c in pred_cols if c.startswith('P_')]
        if blend_cols and all(c in df.columns for c in blend_cols):
            pred_cols = blend_cols
            pred_source = 'BLEND'
        else:
            pred_source = 'ML'

        # Check if columns exist
        missing_cols = [col for col in pred_cols if col not in df.columns]
        if missing_cols or actual_col not in df.columns:
            return {
                'market': market_name,
                'error': f'Missing columns: {missing_cols}',
                'total_predictions': 0
            }

        # Filter by per-market confidence floor.
        # Priority: LEAGUE_MARKET_CONF[league][market] > MARKET_MIN_CONF[market] > global floor.
        global_floor = MARKET_MIN_CONF.get(market_name, self.min_confidence)
        df_market = df.copy()
        df_market['MaxProb'] = df_market[pred_cols].max(axis=1)
        if LEAGUE_MARKET_CONF and 'League' in df_market.columns:
            def _row_floor(league):
                return LEAGUE_MARKET_CONF.get(league, {}).get(market_name, global_floor)
            df_market['_floor'] = df_market['League'].map(_row_floor)
            df_market = df_market[df_market['MaxProb'] >= df_market['_floor']]
            df_market = df_market.drop(columns=['_floor'])
        else:
            df_market = df_market[df_market['MaxProb'] >= global_floor]

        if len(df_market) == 0:
            return {
                'market': market_name,
                'total_predictions': 0,
                'error': f'No predictions above {global_floor:.0%} confidence'
            }

        # Get predicted outcome (highest probability) — use explicit mapping to avoid
        # column-naming fragility (e.g. P_HTFT_H_H split by _ gives wrong tail)
        col_to_outcome = dict(zip(pred_cols, outcomes))
        df_market['PredOutcome'] = df_market[pred_cols].idxmax(axis=1).map(col_to_outcome)

        # Calculate accuracy
        df_market['Correct'] = df_market['PredOutcome'] == df_market[actual_col].astype(str)

        accuracy = df_market['Correct'].mean()
        total = len(df_market)
        correct = df_market['Correct'].sum()

        # Calculate calibration (Brier score)
        brier_scores = []
        for idx, row in df_market.iterrows():
            actual_outcome = str(row[actual_col])
            for i, outcome in enumerate(outcomes):
                predicted_prob = row[pred_cols[i]]
                actual_prob = 1.0 if outcome == actual_outcome else 0.0
                brier_scores.append((predicted_prob - actual_prob) ** 2)

        brier_score = np.mean(brier_scores) if brier_scores else np.nan

        # Calculate ROI using actual bookmaker odds where available
        roi_result = self.calculate_roi(df_market, pred_cols, actual_col, outcomes, market_name=market_name)

        # Confidence distribution
        conf_bins = {
            '60-70%': len(df_market[(df_market['MaxProb'] >= 0.60) & (df_market['MaxProb'] < 0.70)]),
            '70-80%': len(df_market[(df_market['MaxProb'] >= 0.70) & (df_market['MaxProb'] < 0.80)]),
            '80-90%': len(df_market[(df_market['MaxProb'] >= 0.80) & (df_market['MaxProb'] < 0.90)]),
            '90%+': len(df_market[df_market['MaxProb'] >= 0.90]),
        }

        return {
            'market': market_name,
            'total_predictions': total,
            'correct_predictions': int(correct),
            'accuracy': accuracy,
            'brier_score': brier_score,
            'roi_fair': roi_result['roi_fair'],
            'roi_actual': roi_result['roi_actual'],
            'odds_coverage': roi_result['odds_coverage'],
            'avg_confidence': df_market['MaxProb'].mean(),
            'confidence_distribution': conf_bins,
            'type': config['type'],
            'pred_source': pred_source
        }

    def calculate_roi(self, df: pd.DataFrame, pred_cols: List[str],
                     actual_col: str, outcomes: List[str],
                     market_name: str = None) -> dict:
        """
        Calculate ROI using actual bookmaker odds where available,
        falling back to fair odds (1/probability) otherwise.

        Returns dict with roi_actual (bookmaker odds), roi_fair (model odds),
        and odds_coverage (fraction with real odds).
        """
        from odds_utils import get_odds_for_prediction

        total_stake_actual = 0
        total_return_actual = 0
        total_stake_fair = 0
        total_return_fair = 0
        bets_with_odds = 0

        for idx, row in df.iterrows():
            # Get predicted outcome and its probability
            pred_probs = [row[col] for col in pred_cols]
            pred_idx = np.argmax(pred_probs)
            pred_outcome = outcomes[pred_idx]
            pred_prob = pred_probs[pred_idx]

            if pred_prob <= 0:
                continue

            actual_outcome = str(row[actual_col])
            # Conservative estimate: fair odds minus ~10% bookmaker margin
            fair_odds = (1.0 / pred_prob) * 0.9

            # Look up actual bookmaker odds
            actual_odds = None
            if market_name is not None:
                actual_odds = get_odds_for_prediction(row, market_name, pred_outcome)

            # Fair odds ROI (always calculated)
            total_stake_fair += 1.0
            if pred_outcome == actual_outcome:
                total_return_fair += fair_odds

            # Actual odds ROI (when available)
            if actual_odds is not None:
                bets_with_odds += 1
                total_stake_actual += 1.0
                if pred_outcome == actual_outcome:
                    total_return_actual += actual_odds

        roi_fair = ((total_return_fair - total_stake_fair) / total_stake_fair * 100) if total_stake_fair > 0 else 0.0
        roi_actual = ((total_return_actual - total_stake_actual) / total_stake_actual * 100) if total_stake_actual > 0 else None
        coverage = bets_with_odds / total_stake_fair if total_stake_fair > 0 else 0.0

        return {
            'roi_fair': roi_fair,
            'roi_actual': roi_actual,
            'odds_coverage': coverage,
            'bets_with_odds': bets_with_odds,
        }

    def run_analysis(self, output_dir: Path = OUTPUT_DIR) -> pd.DataFrame:
        """Run complete multi-market analysis"""
        print("="*60)
        print(f"MULTI-MARKET BACKTEST ANALYSIS ({self.weeks} weeks)")
        print("="*60)
        print(f"Minimum confidence: {self.min_confidence:.0%}")
        print(f"Markets analyzed: {len(MARKET_CONFIGS)}")
        print()

        # If output_dir is a dated folder, get its parent (outputs/)
        if output_dir.name.startswith('20'):
            base_output_dir = output_dir.parent
            print(f"[INFO] Using base output directory: {base_output_dir}")
        else:
            base_output_dir = output_dir

        # Find week folders (dated folders like 2026-01-02)
        try:
            week_folders = sorted([f for f in base_output_dir.iterdir() if f.is_dir() and f.name.startswith('20')])
        except Exception as e:
            print(f"[ERROR] Could not read output directory: {e}")
            return pd.DataFrame()

        if len(week_folders) == 0:
            print(f"[ERROR] No week folders found in {output_dir}")
            print(f"[INFO] Looking for folders named like: 2026-01-02")
            print(f"[INFO] Make sure predictions have been generated first")
            return pd.DataFrame()

        week_folders = week_folders[-self.weeks:]  # Last N weeks

        print(f"Analyzing weeks: {[f.name for f in week_folders]}\n")

        # Load data
        predictions = self.load_weekly_predictions(week_folders)
        results = self.load_actual_results()

        # Merge
        merged = self.merge_predictions_with_results(predictions, results)

        if len(merged) == 0:
            print("\n[ERROR] No matches found between predictions and results")
            print("[INFO] This happens when:")
            print("  - Predictions are for upcoming matches (not yet played)")
            print("  - Match dates/teams don't exactly match between predictions and database")
            print("  - No completed matches in the selected time period")
            print("\n[TIP] Wait for matches to complete, then run backtest again")
            print("[TIP] Or use older prediction folders that have completed matches")
            return pd.DataFrame()

        # Merge bookmaker odds for realistic ROI
        try:
            from odds_utils import merge_odds_into_df
            merged = merge_odds_into_df(merged)
        except Exception as e:
            print(f"[INFO] Odds not available: {e}")

        # Evaluate each market
        print("\n" + "="*60)
        print("EVALUATING MARKETS")
        print("="*60)

        market_results = []
        for market_name, config in MARKET_CONFIGS.items():
            print(f"\nAnalyzing {market_name}...", end=" ")
            result = self.evaluate_market(merged, market_name, config)
            market_results.append(result)

            if 'error' in result:
                print(f"[SKIP] {result['error']}")
            else:
                print(f"[OK] {result['total_predictions']} predictions, {result['accuracy']:.1%} accuracy")

        # Convert to DataFrame
        df_results = pd.DataFrame(market_results)

        # Filter out markets with errors or no predictions
        df_results = df_results[df_results['total_predictions'] > 0].copy()

        # Sort by accuracy (descending)
        df_results = df_results.sort_values('accuracy', ascending=False)

        # Save results to base output directory
        csv_path = base_output_dir / "market_backtest_analysis.csv"
        df_results.to_csv(csv_path, index=False)
        print(f"\n[OK] Saved analysis to {csv_path}")

        # Generate HTML report
        self.generate_html_report(df_results, base_output_dir)

        return df_results

    def generate_html_report(self, df: pd.DataFrame, output_dir: Path):
        """Generate HTML report with visual analysis"""
        if len(df) == 0:
            return

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Multi-Market Backtest Analysis</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1400px;
            margin: 20px auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 32px;
        }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-bottom: 20px;
        }}
        .stat-card {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .stat-value {{
            font-size: 32px;
            font-weight: bold;
            color: #667eea;
        }}
        .stat-label {{
            color: #666;
            font-size: 14px;
            margin-top: 5px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }}
        th {{
            background: #667eea;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }}
        td {{
            padding: 12px;
            border-bottom: 1px solid #eee;
        }}
        tr:hover {{
            background: #f9f9f9;
        }}
        .acc-excellent {{ color: #22c55e; font-weight: bold; }}
        .acc-good {{ color: #3b82f6; font-weight: bold; }}
        .acc-fair {{ color: #f59e0b; }}
        .acc-poor {{ color: #ef4444; }}
        .roi-positive {{ color: #22c55e; font-weight: bold; }}
        .roi-negative {{ color: #ef4444; }}
        .rank {{
            background: #667eea;
            color: white;
            padding: 4px 8px;
            border-radius: 50%;
            font-weight: bold;
            display: inline-block;
            min-width: 30px;
            text-align: center;
        }}
        .recommendations {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-top: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .rec-good {{
            color: #22c55e;
            font-weight: bold;
        }}
        .rec-avoid {{
            color: #ef4444;
            font-weight: bold;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Multi-Market Backtest Analysis</h1>
        <p>Analysis Period: {self.weeks} weeks | Min Confidence: {self.min_confidence:.0%} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
    </div>

    <div class="summary">
        <div class="stat-card">
            <div class="stat-value">{len(df)}</div>
            <div class="stat-label">Markets Analyzed</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{df['total_predictions'].sum():.0f}</div>
            <div class="stat-label">Total Predictions</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{df['accuracy'].mean():.1%}</div>
            <div class="stat-label">Average Accuracy</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{len(df[df['accuracy'] >= 0.60])}</div>
            <div class="stat-label">Markets >= 60% Acc</div>
        </div>
    </div>

    <h2>Market Performance Ranking</h2>
    <table>
        <thead>
            <tr>
                <th>Rank</th>
                <th>Market</th>
                <th>Type</th>
                <th>Predictions</th>
                <th>Accuracy</th>
                <th>Brier Score</th>
                <th>ROI</th>
                <th>Avg Confidence</th>
            </tr>
        </thead>
        <tbody>
"""

        # Add rows
        for idx, row in df.iterrows():
            rank = list(df.index).index(idx) + 1
            market = row['market']
            market_type = row['type']
            total = int(row['total_predictions'])
            accuracy = row['accuracy']
            brier = row['brier_score']
            roi = row.get('roi_actual') if pd.notna(row.get('roi_actual')) else row.get('roi_fair', 0)
            avg_conf = row['avg_confidence']

            # Accuracy class
            if accuracy >= 0.70:
                acc_class = 'acc-excellent'
            elif accuracy >= 0.60:
                acc_class = 'acc-good'
            elif accuracy >= 0.55:
                acc_class = 'acc-fair'
            else:
                acc_class = 'acc-poor'

            # ROI class
            roi_class = 'roi-positive' if roi > 0 else 'roi-negative'

            html += f"""
            <tr>
                <td><span class="rank">{rank}</span></td>
                <td><strong>{market}</strong></td>
                <td>{market_type}</td>
                <td>{total}</td>
                <td class="{acc_class}">{accuracy:.1%}</td>
                <td>{brier:.3f}</td>
                <td class="{roi_class}">{roi:+.1f}%</td>
                <td>{avg_conf:.1%}</td>
            </tr>
"""

        html += """
        </tbody>
    </table>

    <div class="recommendations">
        <h2>Recommendations</h2>
        <h3 class="rec-good">Markets to Focus On (Accuracy >= 60%)</h3>
        <ul>
"""

        good_markets = df[df['accuracy'] >= 0.60]
        for idx, row in good_markets.iterrows():
            roi_val = row.get('roi_actual') if pd.notna(row.get('roi_actual')) else row.get('roi_fair', 0)
            html += f"<li><strong>{row['market']}</strong>: {row['accuracy']:.1%} accuracy, {int(row['total_predictions'])} predictions, ROI: {roi_val:+.1f}%</li>\n"

        html += """
        </ul>
        <h3 class="rec-avoid">Markets to Avoid (Accuracy < 55%)</h3>
        <ul>
"""

        poor_markets = df[df['accuracy'] < 0.55]
        for idx, row in poor_markets.iterrows():
            html += f"<li><strong>{row['market']}</strong>: {row['accuracy']:.1%} accuracy, {int(row['total_predictions'])} predictions</li>\n"

        html += """
        </ul>
    </div>
</body>
</html>
"""

        html_path = output_dir / "market_backtest_analysis.html"
        html_path.write_text(html, encoding='utf-8')
        print(f"[OK] Saved HTML report to {html_path}")


def run_market_backtest(weeks: int = 4, min_confidence: float = 0.90,
                        use_historical: bool = True, by_league: bool = False):
    """
    Run multi-market backtest analysis

    Args:
        weeks: Number of weeks to analyze
        min_confidence: Minimum confidence threshold (0.0-1.0)
        use_historical: If True, run walk-forward backtest on historical data (default)
                       If False, analyze recent prediction folders
        by_league: If True, also print per-league accuracy/ROI breakdown
    """
    backtester = MarketBacktester(weeks=weeks, min_confidence=min_confidence, use_historical=use_historical)

    if use_historical:
        # Run walk-forward backtest on historical data
        results = backtester.run_historical_backtest(by_league=by_league)
    else:
        # Analyze recent prediction folders
        results = backtester.run_analysis()

    if len(results) > 0:
        print("\n" + "="*60)
        print("TOP 10 MARKETS BY ACCURACY")
        print("="*60)
        for idx, row in results.head(10).iterrows():
            roi_val = row.get('roi_actual') if pd.notna(row.get('roi_actual')) else row.get('roi_fair', 0)
            print(f"{list(results.index).index(idx)+1:2d}. {row['market']:20s} - {row['accuracy']:.1%} ({int(row['total_predictions'])} predictions, ROI: {roi_val:+.1f}%)")

        print("\n" + "="*60)
        print("ANALYSIS COMPLETE")
        print("="*60)
        print("Files generated:")
        print("  - market_backtest_analysis.csv")
        print("  - market_backtest_analysis.html")

    return results


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Multi-Market Backtest Analysis')
    parser.add_argument('--weeks', type=int, default=4, help='Number of weeks to analyze (default: 4)')
    parser.add_argument('--min-confidence', type=float, default=0.90, help='Minimum confidence threshold 0.0-1.0 (default: 0.90)')
    parser.add_argument('--no-historical', action='store_true', help='Use recent predictions instead of historical backtest')
    parser.add_argument('--by-league', action='store_true', help='Also print per-league accuracy/ROI breakdown')
    args = parser.parse_args()

    use_historical = not args.no_historical
    run_market_backtest(weeks=args.weeks, min_confidence=args.min_confidence,
                        use_historical=use_historical, by_league=args.by_league)
